# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Get latest Corretto URL
      id: get-latest-corretto-url
      run: >-
        echo "::set-output name=URL::$(curl -LIs -o /dev/null -w
        %{url_effective}
        https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.tar.gz)"
    - uses: actions/cache@v2
      id: corretto-cache
      name: Restore Corretto
      with:
        path: ./amazon-corretto-8-x64-linux-jdk.tar.gz
        key: >-
          ${{ runner.os }}-corretto-${{
          steps.get-latest-corretto-url.outputs.URL }}
    - name: Download AWS Corretto
      if: steps.corretto-cache.outputs.cache-hit != 'true'
      run: >-
        wget
        https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.tar.gz
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: jdkfile
        java-version: '8'
        architecture: x64
        jdkFile: ./amazon-corretto-8-x64-linux-jdk.tar.gz

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
